/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cxd_jni_TestJNI */

#ifndef _Included_com_cxd_jni_TestJNI
#define _Included_com_cxd_jni_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cxd_jni_TestJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cxd_jni_TestJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
